
shader
	name "undefined"
	single_sided
	diffuse
		color 0.85 0.85 0.85
	end
	geometry
		smooth_angle 0
	end
end

shader
	name "light"
	virtual_light
	side "outer"
	emission
	    color 150 150 150
	end
end


shader
	name "rightwall"
	single_sided	
	diffuse
		color 0.85 0.15 0.15
	end
	geometry
		smooth_angle 0
	end
end


shader
	name "leftwall"
	single_sided
	diffuse
		color 0.15 0.85 0.15
	end
	geometry
		smooth_angle 0
	end
end

shader
	name "Sphere1"
	glossy
		color 0.8 0.8 0.8
	end
	roughness
	    color 0.21 0.21 0.21
	end
	volume
		ior 100
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere2"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.17 0.17 0.17
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere3"

	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.13 0.13 0.13
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere4"
	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.09 0.09 0.09
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere5"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.05 0.05 0.05
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere6"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.01 0.01 0.01
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere7"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.21 0.105 0
	end
	geometry
		smooth_angle 30
		ignore_vertex_vector 0
	end
end

shader
	name "Sphere8"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.17 0.085 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere9"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.13 0.065 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere10"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.09 0.045 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere11"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.05 0.025 0.0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere12"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.01 0.005 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere13"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.21 0.0525 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere14"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.17 0.0425 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere15"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.13 0.0325 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere16"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.09 0.0225 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere17"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.05 0.0125 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere18"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.01 0.0025 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end



shader
	name "Sphere19"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.21 0.02625 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere20"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.17 0.02625 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere21"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.13 0.01625 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere22"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.09 0.01125 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere23"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.05 0.00625 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere24"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.01 0.00125 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere25"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.21 0.013125 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere26"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.17 0.010625 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere27"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.13 0.008125 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere28"	
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.09 0.005625 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere29"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.05 0.003125 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end

shader
	name "Sphere30"
	glossy
		color 0.8 0.8 0.8
	end
	volume
		ior 100
	end
	roughness
	    color 0.01 0.000625 0
	end
	geometry
		ignore_vertex_vector 0
		smooth_angle 30
	end
end