
shader
	name               "undefined"
	surface_shader
		lambertian
			color 0.85 0.85 0.85
		end
	end
	geometry_shader
		smooth_vertex_vector 1
	end
end

shader
	name "light"
	surface_shader
		virtual_light 1
		sideness      "face"
		emissive
		    color 150 150 150
		end
	end
	surface_shader
		sideness      "back"
		emissive
		    color 0 0 0 5 10 15
		end
	end
end

shader
	name               "floor"
	surface_shader
		lambertian
			color 0.9 0.9 0.9
		end
	end
	geometry_shader
		smooth_vertex_vector 1
	end
end

shader
	name "rearwall"
	surface_shader
		lambertian
			color 0.85 0.85 0.85
		end
	end
	geometry_shader
		smooth_vertex_vector 1
	end
end

shader
	name "rightwall"
	surface_shader
		lambertian
			color 0.85 0.15 0.15
		end
	end
	geometry_shader
		smooth_vertex_vector 1
	end
end


shader
	name "leftwall"
	surface_shader
		lambertian
			color 0.15 0.85 0.15
		end
	end
	geometry_shader
		smooth_vertex_vector 1
	end
end

shader
	name "rightWall"
	surface_shader
		lambertian
			color 0.45 0.15 0.85
		end
	end
	geometry_shader
		smooth_vertex_vector 1
	end
end

shader
	name               "ceiling"
	surface_shader
		lambertian
			color         0.85 0.85 0.85
		end
	end
	geometry_shader
		smooth_vertex_vector 1
	end
end

shader
	name               "Sphere1"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.21 0.21 0.21
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere2"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.17 0.17 0.17
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere3"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.13 0.13 0.13
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere4"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.09 0.09 0.09
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere5"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.05 0.05 0.05
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere6"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.01 0.01 0.01
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere7"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.21 0.21 0.21
		end
	end
	geometry_shader
		smooth_vertex_vector 0
		ignore_vertex_vector 0
	end
end

shader
	name               "Sphere8"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.17 0.17 0.17
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere9"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.13 0.13 0.13
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere10"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.09 0.09 0.09
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere11"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.05 0.05 0.05
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere12"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.01 0.01 0.01
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere13"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.21 0.21 0.21
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere14"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.17 0.17 0.17
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere15"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.13 0.13 0.13
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere16"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.09 0.09 0.09
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere17"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.05 0.05 0.05
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere18"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.01 0.01 0.01
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere19"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.21 0.21 0.21
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere20"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.17 0.17 0.17
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere21"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.13 0.13 0.13
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere22"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.09 0.09 0.09
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere23"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.05 0.05 0.05
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere24"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.01 0.01 0.01
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere25"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.21 0.21 0.21
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere26"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.17 0.17 0.17
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere27"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.13 0.13 0.13
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere28"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.09 0.09 0.09
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere29"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.05 0.05 0.05
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end

shader
	name               "Sphere30"
	surface_shader
		glossy
			color 0.8 0.8 0.8
		end
		ior
			color 100 100 100
		end
		roughness
		    color 0.01 0.01 0.01
		end
	end
	geometry_shader
		ignore_vertex_vector 0
		smooth_vertex_vector 0
	end
end
