render

	clamp        1 1 1
	gamma        2.2
	exposure     1
	image_path   ""

	final_gather
		sample       128
		ray_depth    8
		photon_depth 16
		bounce       2
		radius       0.2
		resolution   0.001
	end
end
